# https://leetcode.com/problems/increasing-triplet-subsequence/description/
from typing import List, Tuple
from unittest import TestCase, main


class Solution:
    def increasingTriplet(self, nums: List[int]) -> bool:
        arr = [2147483648, 2147483648]

        # edge case
        if len(nums) < 3:
            return False

        for n in nums:
            if n <= arr[0]:
                arr[0] = n
                continue
            if n <= arr[1]:
                arr[1] = n
                continue
            # now we can say we found arr[0] < arr[1] < n
            return True

        return False


class Test(TestCase):
    s = Solution()
    data: List[Tuple[List[int], bool]] = [
        (
            [
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
            ],
            False,
        ),
        ([2, 1, 5, 0, 4, 6], True),
        ([1, 2, 3, 4, 5], True),
        ([5, 4, 3, 2, 1], False),
    ]

    def test_solution(self):
        for nums, expected in self.data:
            self.assertEqual(self.s.increasingTriplet(nums), expected)


if __name__ == "__main__":
    main()
